config/routes.rb
Exercicio::Application.routes.draw do
  resources :clients do
    resources :orders
  end

  resources :products

  root :to => 'root#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :orders

  validates :name, :address, :phone, :presence => true
  validates :phone, :format => { :with => /\([0-9]{2}\) [0-9]{4}\-[0-9]{4}/ }

  def to_s
    name
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :client
  belongs_to :product

  validates_associated :client, :product
  validates :amount, :presence => true, :numericality => true

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders

  validates :name, :price, :presence => true
  validates :price, :numericality => true
  validates :name, :length => { :maximum => 25 }
  validates :description, :length => { :maximum => 500 }

  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  # GET /clients
  def index
    @clients = Client.all
  end

  # GET /clients/id
  def show
    @client = Client.find(params[:id])
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/id/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  def create
    @client = Client.new(params[:client])
    if(@client.save)
      redirect_to @client, notice: 'Cliente cadastrado com sucesso.'
    else
      render 'new'
    end
      
  end

  # PUT /clients/id
  def update
    @client = Client.find(params[:id])
    if( @client.update_attributes(params[:client]) )
      redirect_to @client, notice: 'Cliente alterado com sucesso.'
    else
      render 'edit'
    end
  end

  # DELETE /clients/id
  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    redirect_to clients_url
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @client = Client.find(params[:client_id])
    @orders = @client.orders
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(params[:order])
    @order.client_id = params[:client_id]
    if(@order.save)
      redirect_to client_orders_path(@order.client), notice: 'Compra cadastrada com sucesso.'
    else
      render 'new'
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if( @order.update_attributes(params[:client]) )
      redirect_to client_orders_path(@order.client), notice: 'Compra alterada com sucesso.'
    else
      render 'edit'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.delete
    redirect_to client_orders_path(@order.client)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/id
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/id/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  def create
    @product = Product.new(params[:product])
    if(@product.save)
      redirect_to @product, notice: 'Produto cadastrado com sucesso.'
    else
      render 'new'
    end
  end

  # PUT /products/id
  def update
    @product = Product.find(params[:id])
    if( @product.update_attributes(params[:product]) )
      redirect_to @product, notice: 'Produto alterado com sucesso.'
    else
      render 'edit'
    end
  end

  # DELETE /clients/id
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url
  end

end

app/controllers/root_controller.rb
class RootController < ApplicationController

  # GET /index
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.haml
= form_for(@client) do |f|
  
  - if @client.errors.any?
    %b
      = pluralize(@client.errors.count, "erro(s)")
      nao permitiu(ram) que esse cliente seja salvo:
    %center
      %table.commom    
        - @client.errors.full_messages.each do |msg|
          %tr
            %td
              %i
              *
              = msg
       
  %br
  %center
    %table.commom
      %tr
        %td
          .field
            %b
              = f.label 'Nome:'
        %td
          = f.text_field :name
      %tr
        %td
          .field
            %b
              = f.label 'Endereco:'
        %td
          = f.text_field :address
      %tr
        %td
          .field
            %b
              = f.label 'Telefone:'
        %td
          - if @client.new_record?
            = f.text_field :phone, :value=>'() -', :size=>10
          - else
            = f.text_field :phone, :value=>@client.phone, :size=>10
    %br
    .actions
      = f.submit :value => 'Cadastrar'

app/views/clients/edit.html.haml
%h1 Alteracao de Cliente

= render 'form'

= link_to 'Ver', @client
|
= link_to 'Voltar', clients_path

app/views/clients/index.html.haml
%h1 Clientes Cadastrados

%p
  = link_to 'Voltar', root_path
  |
  = link_to 'Novo Cliente', new_client_path

%br

%center
  %table.list
    - @clients.each do |client|
      %tr
        %td.item
          = link_to client.name, client, :class=>'table'
        %td.options
          = link_to image_tag('view.png'), client
            
          = link_to image_tag('edit.png'), edit_client_path(client)
           
          = link_to image_tag('delete.png'), client, confirm: 'Tem certeza que deseja excluir?', method: :delete

%br
%p
  = link_to 'Voltar', root_path
  |
  = link_to 'Novo Cliente', new_client_path

app/views/clients/new.html.haml
%h1 Novo Cliente

= render 'form'

= link_to 'Voltar', clients_path

app/views/clients/show.html.haml
%p#notice= notice

%h1= @client.name

%center
  %table.commom
    %tr
      %td  
        %b Endereco:
      %td
        = @client.address
    %tr
      %td  
        %b Telefone:
      %td
        = @client.phone

%p
  %b= link_to 'COMPRAS', client_orders_path(@client)

%p
  = link_to 'Voltar', clients_path
  |
  = link_to 'Alterar', edit_client_path(@client)

app/views/layouts/application.html.haml
%html
  %head
    %title Mercadinho Dona Flor
    
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .main
      = yield

app/views/orders/_form.html.haml
= form_for([:client,@order]) do |f|
  
  - if @order.errors.any?
    %b
      = pluralize(@order.errors.count, "erro(s)")
      nao permitiu(ram) que essa compra seja salva:
    %center
      %table.commom    
        - @order.errors.full_messages.each do |msg|
          %tr
            %td
              %i
              *
              = msg
       
  %br
  %center
    %table.commom
      %tr
        %td
          %b
            Cliente:
        %td
          = Client.find(params[:client_id])
      %tr
        %td
          .field
            %b
              = f.label 'Produto:'
        %td
          = f.select :product_id, Product.all.collect { |product| [ product.name, product.id ] }
      %tr
        %td
          .field
            %b
              = f.label 'Quantidade:'
        %td
          = f.text_field :amount, :size=>5
      
      %tr
        %td
          .field
            %b
              = f.label 'Data:'
        %td
          = date_select(:order, :date, :order => [:day, :month, :year] ) 
      
    %br
    .actions
      = f.submit :value=>'Cadastrar'

app/views/orders/edit.html.haml
%h1 Alteracao de Compra

= render 'form'

= link_to 'Voltar', client_orders_path(@order.client)

app/views/orders/index.html.haml
%h1= @client.name

%p#notice= notice

%p
  = link_to 'Voltar', @client
  |
  = link_to 'Nova Compra', new_client_order_path

%br

%center
  %table.list
    %th.list Produto
    %th.list Preco
    %th.list Qtde
    %th.list Data
    %th.list
    - @orders.each do |order|
      %tr
        %td.item
          = order.product
        %td.item
          = order.product.price
        %td.item
          = order.amount
        %td.item
          = order.date
        %td.options
          = link_to image_tag('edit.png'), edit_client_order_path(@client,order)
           
          = link_to image_tag('delete.png'), [@client,order], confirm: 'Tem certeza que deseja excluir?', method: :delete

%br
%p
  = link_to 'Voltar', @client
  |
  = link_to 'Nova Compra', new_client_order_path

app/views/orders/new.html.haml
%h1 Nova Compra

= render 'form'

= link_to 'Voltar', client_orders_path

app/views/products/_form.html.haml
= form_for(@product) do |f|
  
  - if @product.errors.any?
    %b
      = pluralize(@product.errors.count, "erro(s)")
      nao permitiu(ram) que esse produto seja salvo:
    %center
      %table.commom    
        - @product.errors.full_messages.each do |msg|
          %tr
            %td
              %i
              *
              = msg
       
  %br
  %center
    %table.commom
      %tr
        %td
          .field
            %b
              = f.label 'Nome:'
        %td
          = f.text_field :name
      %tr
        %td
          .field
            %b
              = f.label 'Descricao:'
        %td
          = f.text_field :description
      %tr
        %td
          .field
            %b
              = f.label 'Preco:'
        %td
          = f.text_field :price,:size=>5
    %br
    .actions
      = f.submit :value => 'Cadastrar'

app/views/products/edit.html.haml
%h1 Alteracao de Produto

= render 'form'

= link_to 'Ver', @product
|
= link_to 'Voltar', products_path

app/views/products/index.html.haml
%h1 Produtos Cadastrados

%p
  = link_to 'Voltar', root_path
  |
  = link_to 'Novo Produto', new_product_path

%br

%center
  %table.list
    - @products.each do |product|
      %tr
        %td.item
          = link_to product.name, product, :class=>'table'
        %td.options
          = link_to image_tag('view.png'), product
            
          = link_to image_tag('edit.png'), edit_product_path(product)
           
          = link_to image_tag('delete.png'), product, confirm: 'Tem certeza que deseja excluir?', method: :delete

%br
%p
  = link_to 'Voltar', root_path
  |
  = link_to 'Novo Produto', new_product_path

app/views/products/new.html.haml
%h1 Novo Produto
= render 'form'
= link_to 'Voltar', products_path

app/views/products/show.html.haml
%p#notice= notice
%h1= @product.name
%p
  %b Descricao:
  = @product.description
%p
  %b Preco:
  = @product.price
= link_to 'Alterar', edit_product_path(@product)
| #{link_to 'Voltar', products_path}

app/views/root/index.html.haml
= image_tag('logo.png')
%br
%br
%br

%center
  %table.main
    %tr
      %th
        %h1 CLIENTES / COMPRAS
      %th
        %h1 PRODUTOS
    %tr
      %td
        = link_to 'Cadastrar novo cliente', new_client_path
        %br
        = link_to 'Acessar cadastro de clientes', clients_path
      %td
        = link_to 'Cadastrar novo produto', new_product_path
        %br
        = link_to 'Acessar cadastro de produtos', products_path